### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by christianrd**
Integration with Travis CI and updated laravel version.

### CODE REVIEW

**Comment by alblandino** [comment]
@christianrd 

I am seeing that you are adding continuous integration into the project.
In travis-ci is your own account or one of the community?

**Comment by christianrd** [comment]
Hi, @jblandino 

Yes it's my own account on Travis, but we can use this account or create a new account for community.
For more information, please inbox me on facebook.

**Comment by christianrd** [comment]
@jblandino please don't merge this pull request.

**Comment by alblandino** [comment]
Ok, not problem.

**Pull request closed without merging**
